Screens:
  Library Settings:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Horizontal Container:
          Control: GroupContainer@1.3.0
          Variant: AutoLayout
          Properties:
            Height: =653
            LayoutDirection: =LayoutDirection.Horizontal
            Width: =1366
            Y: =114
          Children:
            - buttonsContainer:
                Control: GroupContainer@1.3.0
                Variant: ManualLayout
                Children:
                  - btn_max_time_rent:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Max czas wypożyczenia"
                        Width: =300
                        X: =20
                        Y: =14
                  - btn_max_rent:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Max liczba wypożyczeń"
                        Width: =300
                        X: =20
                        Y: =79
                  - btn_reservations_off:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Wł/wył rezerwacje książek"
                        Width: =300
                        X: =20
                        Y: =138
                  - btn_notifications_email:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: |-
                          ="Powiadomienia Email
                          "
                        Width: =300
                        X: =20
                        Y: =200
                  - btn_reservations_cancellation:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Wł/wył anulowanie rezerwacji"
                        Width: =300
                        X: =20
                        Y: =258
                  - btn_default_lang:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Domyślny język interfejsu"
                        Width: =300
                        X: =20
                        Y: =314
                  - btn_darkmode:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Tryb ciemny"
                        Width: =300
                        X: =20
                        Y: =366
                  - btn_open_hours:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Godziny otwarcia biblioteki"
                        Width: =300
                        X: =20
                        Y: =425
                  - btn_others:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Pozostałe ustawienia"
                        Width: =300
                        X: =20
                        Y: =481
                  - btn_technical_mode:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Tryb techniczny"
                        Width: =300
                        X: =20
                        Y: =540
                  - btn_reg_off:
                      Control: Classic/Button@2.2.0
                      Properties:
                        BorderColor: =ColorFade(Self.Fill, -15%)
                        Color: =RGBA(255, 255, 255, 1)
                        DisabledBorderColor: =RGBA(166, 166, 166, 1)
                        Fill: =RGBA(56, 96, 178, 1)
                        Font: =Font.'Open Sans'
                        HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                        HoverColor: =RGBA(255, 255, 255, 1)
                        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                        PressedBorderColor: =Self.Fill
                        PressedColor: =Self.Fill
                        PressedFill: =Self.Color
                        Size: =13
                        Text: ="Zablokuj możliwość rejestracji"
                        Width: =300
                        X: =20
                        Y: =596
            - optionsContainer:
                Control: GroupContainer@1.3.0
                Variant: ManualLayout
                Properties:
                  FillPortions: =3
                  LayoutMinWidth: =300
      - MenuLeftNav_17:
          Control: CanvasComponent
          ComponentName: MenuLeftNav
          Properties:
            AdminAccess: =varAdminAccess
            ExpandMenu: =
            HamburgerMenuColor: =Color.Blue
            Height: =If(!MenuLeftNav_17.showMenuProp, 50, App.Height)
            LoggedUser: =varLoggedUser
            MenuBkgColor: =RGBA(220,220,220,1)
            MenuColor: =Color.Purple
            MenuItems: |
              =Table(
                  {
                      MenuLabel: "Dashboard",
                      MenuIcon: Icon.Home,
                      MenuScreenNavigate: Dashboard,
                      MenuID: 1,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Book Catalog",
                      MenuIcon: Icon.Database,
                      MenuScreenNavigate: 'Book Catalog',
                      MenuID: 2,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Book Details",
                      MenuIcon: Icon.ListScrollWatchlist,
                      MenuScreenNavigate: 'Book Details',
                      MenuID: 3,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Your Books",
                      MenuIcon: Icon.Notebook,
                      MenuScreenNavigate: 'Your Books',
                      MenuID: 4,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Wishlist / Favorites",
                      MenuIcon: Icon.Heart,
                      MenuScreenNavigate: 'Wishlist / Favorites',
                      MenuID: 5,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Book Reservations",
                      MenuIcon: Icon.CalendarBlank,
                      MenuScreenNavigate: 'Book Reservations',
                      MenuID: 6,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Borrowing History",
                      MenuIcon: Icon.History,
                      MenuScreenNavigate: 'Borrowing History',
                      MenuID: 7,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Library Ranking",
                      MenuIcon: Icon.Globe,
                      MenuScreenNavigate: 'Library Ranking',
                      MenuID: 8,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "User Profile",
                      MenuIcon: Icon.Person,
                      MenuScreenNavigate: 'User Profile',
                      MenuID: 9,
                      SubMenu: Table()
                  },
                  {
                      MenuLabel: "Admin Panel",
                      MenuIcon: Icon.Manufacture,
                      //MenuScreenNavigate: 'Admin Panel',
                      MenuID: 10,
                      VisibleSubMenu: true,
                      SubMenu: Table(
                          {
                              MenuLabel: "Add Book",
                              MenuIcon: Icon.AddDocument,
                              MenuScreenNavigate: 'Add Book',
                              MenuID: 1
                          },
                          {
                              MenuLabel: "Edit Book",
                              MenuIcon: Icon.ColorPicker,
                              MenuScreenNavigate: 'Edit Book',
                              MenuID: 2
                          },
                          {
                              MenuLabel: "Delete Book",
                              MenuIcon: Icon.ClearDrawing,
                              MenuScreenNavigate: 'Delete Book',
                              MenuID: 3
                          },
                          {
                              MenuLabel: "Manage Users",
                              MenuIcon: Icon.People,
                              MenuScreenNavigate: 'Manage Users',
                              MenuID: 4
                          },
                          {
                              MenuLabel: "Manage Loans",
                              MenuIcon: Icon.Currency,
                              MenuScreenNavigate: 'Manage Loans',
                              MenuID: 5
                          },
                          {
                              MenuLabel: "Manage Reservations",
                              MenuIcon: Icon.PhotosPictures,
                              MenuScreenNavigate: 'Manage Reservations',
                              MenuID: 6
                          },
                          {
                              MenuLabel: "Library Settings",
                              MenuIcon: Icon.Settings,
                              MenuScreenNavigate: 'Library Settings',
                              MenuID: 7
                          },
                          {
                              MenuLabel: "Check Log",
                              MenuIcon: Icon.Warning,
                              MenuScreenNavigate: 'Check Log',
                              MenuID: 8
                          }
                      )
                  }
              )
            SetMenuWidth: =300
            Width: =MenuLeftNav_17.MenuWidth
      - PageTitle_17:
          Control: CanvasComponent
          ComponentName: PageTitle
          Properties:
            Height: =50
            Width: =200
            X: =1166
            screenInfo: =App.ActiveScreen
